feat: RSS-ECOMM-3_01, RSS-ECOMM-3_02, RSS-ECOMM-3_03: Fetch and Display Product List, Display Prices with and Without Discount, Implement Robust Filtering Options
playoffthecuff/eCommerce-App pull request #48
Opened 2024-05-29 21:41 UTC by hrybach-oleksiy

# Task

[RSS-ECOMM-3_01](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_01.md)
[RSS-ECOMM-3_02](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_02.md)
[RSS-ECOMM-3_03](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_03.md)

# Description

- [x] The application successfully fetches a list of products from the commercetools API, including the essential details: name, image, and description.
- [x] The fetched products are displayed on the Catalog Product page in an organized, easy-to-browse manner 🧹.
- [x] Each product card includes the product's image, name, and description, and these elements are easy to identify and understand by users 👥.
- [x] Both the original price and the discounted price are clearly displayed for discounted products.
- [x] The discounted price is visually distinct and clearly indicates that it is the current price the customer needs to pay.
- [x] If the original price is displayed, it should be marked in a way that clearly communicates that it is not the current price (e.g., strikethrough).
- [x] A robust set of filters is available, allowing users to refine the product list based on various attributes like price range, brand, color, size, etc.
- [x] Applying a filter updates the product list to show only products that match the selected filter criteria. This updating should be done using the commercetools API.
- [x] It's clear to the user which filters are currently applied.
- [x] There is a clear and easy way for users to reset the filters.

# Demo

![image](https://github.com/playoffthecuff/eCommerce-App/assets/84387553/8b1d697b-b06d-4dd8-9b56-6221662ee9c4)
![image](https://github.com/playoffthecuff/eCommerce-App/assets/84387553/e31ff6f9-983a-448b-afc4-642a8e81cfbc)

# How Has This Been Tested?

not tested yet

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added tests to cover my changes

2024-05-30 07:10 UTC, AleksandrGorodetskii approved these changes

2024-05-30 10:10 UTC, SwallowOnes requested changes
Привет,  нужно подправить, пока проблематично проверять.

2024-05-30 10:21 UTC, SwallowOnes reviewed
Соре я там не комент выбрал а реквест чейнджес

2024-05-30 10:28 UTC, SwallowOnes approved these changes

2024-05-30 16:31 UTC, kat2709 approved these changes

2024-05-31 13:27 UTC, AleksandrGorodetskii approved these changes

2024-05-31 13:27 UTC, hapikus approved these changes

2024-05-31 13:51 UTC, kat2709 approved these changes

2024-05-31 14:47 UTC, SwallowOnes approved these changes

2024-05-31 17:07 UTC, merged